var Events = {
	
	NEW_USER_ADDITION : 'NEW_USER_ADDITION',
	REGISTRATION_FAILED : 'REGISTRATION_FAILED', 
	USER_REGISTERED : 'USER_SUCCESSFULLY_REGISTERED',
	LOGIN_ATTEMPT : 'LOGIN',
	LOGIN_FAILED : 'LOGIN_FAILED',
	LOGIN_SUCCESSFULL : 'USER_LOGGED_IN',
	NEW_CHAT_CREATION: 'NEW_CHAT_CREATING',
	CHAT_CREATION_FAILED : 'CHAT_CREATION_FAILED',
	CHAT_LIST_UPDATED: 'CHAT_LIST_UPDATED',
	CHAT_CREATED: 'CHAT_CREATED',
	JOINING_CHAT : 'JOIN_CHAT',
	CHAT_JOINING_FAILED : 'USER_JOINING_FAILED',
	USER_JOINED_CHAT: 'ON_USER_JOINED',
	LEAVING_CHAT: 'LEAVING_CHAT',
	CHAT_LEAVING_FAILED : 'USER_LEAVING_FAILED',
	USER_LEFT_CHAT: 'USER_LEFT_CHAT',
	ADDING_NEW_MESSAGE: 'ON_MESSAGE_ADDED',
	MESSAGE_ADDING_FAILED: 'MESSAGE_ADDING_FAILED',
	MESSAGE_ADDED: 'MESSAGE_ADDED'
}

if (typeof define !== 'function') {
    var define = require('amdefine')(module);
}

define(function() {
	return Events;
});